# Uncomment the next line to define a global platform for your project
platform :macos, '10.10'

target 'TICDemo_Mac' do
  pod 'TXIMSDK_Mac', '~> 4.4.627'
  pod 'TXLiteAVSDK_TRTC_Mac', '~> 6.5.7272'
end
