# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TICDemo' do
  pod 'TEduBoard_iOS', '2.3.7'
  pod 'TXIMSDK_iOS', '4.5.111'
  pod 'TXLiteAVSDK_TRTC', '6.7.7734'
end
